version: '3.1'
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./src/main/resources:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
